version: '3.8'

services:
  alert-scoring-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.13
    
    container_name: alert-scoring-api
    
    ports:
      - "${API_PORT:-8000}:8000"
    
    volumes:
      - ./data/trained_models:/app/data/trained_models:ro
      - ./logs:/app/logs
      - ./data:/app/data:ro
    
    env_file:
      - .env
    
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_WORKERS=${API_WORKERS:-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RANDOM_SEED=${RANDOM_SEED:-42}
      - ALERT_SCORER_PATH=/app/data/trained_models/alert_scorer_v1.0.0.txt
      - ALERT_RANKER_PATH=/app/data/trained_models/alert_ranker_v1.0.0.txt
      - CLUSTER_SCORER_PATH=/app/data/trained_models/cluster_scorer_v1.0.0.txt
    
    restart: unless-stopped
    
    mem_limit: 4g
    mem_reservation: 1g
    cpus: 2.0
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    
    networks:
      aml-miner-network:
        aliases:
          - api
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3
    
    depends_on:
      clickhouse:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: alert-scoring-clickhouse
    
    ports:
      - "${CLICKHOUSE_PORT:-8123}:8123"
      - "9000:9000"
    
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./packages/storage/schema:/docker-entrypoint-initdb.d:ro
    
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DATABASE:-alert_scoring}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    
    restart: unless-stopped
    
    mem_limit: 2g
    mem_reservation: 512m
    
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    
    networks:
      aml-miner-network:
        aliases:
          - clickhouse
          - database
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  aml-miner-network:
    driver: bridge
    name: aml-miner-network

volumes:
  clickhouse_data:
    driver: local