alert_scorer:
  num_leaves: 31
  max_depth: -1
  learning_rate: 0.05
  n_estimators: 100
  min_child_samples: 20
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 0.1
  random_state: 42
  objective: binary
  metric: auc
  verbosity: -1
  n_jobs: -1

alert_ranker:
  num_leaves: 31
  max_depth: -1
  learning_rate: 0.05
  n_estimators: 100
  min_child_samples: 20
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  objective: lambdarank
  metric: ndcg
  ndcg_eval_at: [5, 10, 20]
  verbosity: -1
  n_jobs: -1

cluster_scorer:
  num_leaves: 31
  max_depth: -1
  learning_rate: 0.05
  n_estimators: 100
  min_child_samples: 20
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 0.1
  random_state: 42
  objective: binary
  metric: auc
  verbosity: -1
  n_jobs: -1

feature_engineering:
  temporal_features:
    - hour_of_day
    - day_of_week
    - is_weekend
    - time_since_last_alert
  
  amount_features:
    - amount_raw
    - amount_log
    - amount_z_score
    - amount_percentile
  
  network_features:
    - in_degree
    - out_degree
    - pagerank
    - betweenness_centrality
  
  cluster_features:
    - cluster_size
    - cluster_density
    - pattern_match_score

training:
  validation_split: 0.2
  test_split: 0.1
  cv_folds: 5
  early_stopping_rounds: 50
  min_training_samples: 10000